# Generated by Django 6.0.1 on 2026-01-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('job_portal', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_data', models.JSONField()),
                ('resume_pdf', models.FileField(upload_to='resumes/')),
            ],
        ),
    ]
